from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    '''
    class houses the gui
    '''
    def setupUi(self, mainWindow):
        '''
        function sets up the gui
        '''
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 524)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_GradingCalculator = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_GradingCalculator.setGeometry(QtCore.QRect(10, 10, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_GradingCalculator.setFont(font)
        self.label_GradingCalculator.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_GradingCalculator.setObjectName("label_GradingCalculator")
        self.line_H = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_H.setGeometry(QtCore.QRect(10, 50, 781, 20))
        self.line_H.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_H.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_H.setObjectName("line_H")
        self.label_num = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num.setGeometry(QtCore.QRect(10, 70, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_num.setFont(font)
        self.label_num.setObjectName("label_num")
        self.textEdit_num = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_num.setGeometry(QtCore.QRect(260, 70, 341, 31))
        self.textEdit_num.setObjectName("textEdit_num")
        self.label_num_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num_2.setGeometry(QtCore.QRect(10, 130, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_num_2.setFont(font)
        self.label_num_2.setObjectName("label_num_2")
        self.textEdit_num_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_num_2.setGeometry(QtCore.QRect(260, 130, 341, 31))
        self.textEdit_num_2.setObjectName("textEdit_num_2")
        self.pushButton_Store = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Store.setGeometry(QtCore.QRect(620, 70, 161, 31))
        self.pushButton_Store.setObjectName("pushButton_Store")
        self.pushButton_Calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(620, 130, 161, 31))
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.listWidget_Scores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_Scores.setGeometry(QtCore.QRect(20, 200, 761, 251))
        self.listWidget_Scores.setObjectName("listWidget_Scores")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_Scores.addItem(item)
        self.label_Error = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(260, 170, 341, 16))
        self.label_Error.setText("")
        self.label_Error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Error.setObjectName("label_Error")
        self.pushButton_Clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Clear.setGeometry(QtCore.QRect(690, 460, 93, 28))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_GradingCalculator.setText(_translate("mainWindow", "Grading Calculator"))
        self.label_num.setText(_translate("mainWindow", "Enter Number of Students:"))
        self.label_num_2.setText(_translate("mainWindow", "Enter (x) Scores: (1 Space)"))
        self.pushButton_Store.setText(_translate("mainWindow", "Store"))
        self.pushButton_Calculate.setText(_translate("mainWindow", "Calculate!"))
        __sortingEnabled = self.listWidget_Scores.isSortingEnabled()
        self.listWidget_Scores.setSortingEnabled(False)
        item = self.listWidget_Scores.item(0)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(1)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(2)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(3)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(4)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(5)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(6)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(7)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(8)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(9)
        item.setText(_translate("mainWindow", ""))
        item = self.listWidget_Scores.item(10)
        item.setText(_translate("mainWindow", ""))
        self.listWidget_Scores.setSortingEnabled(__sortingEnabled)
        self.pushButton_Clear.setText(_translate("mainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
